---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
   - role: prepare

- hosts: master[0]
  become: yes
  environment:
    - K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  roles:
    - { role: metallb, tags: 'metallb' }
    - { role: nfs-subdir-external-provisioner, tags: 'nfs-subdir-external-provisioner' }
    - { role: pihole, tags: 'pihole' }
    - { role: monitoring, tags: 'monitoring' }
    - { role: plex, tags: 'plex' }
