---

- name: Create metallb-system namespace
  community.kubernetes.k8s:
    name: metallb-system
    api_version: v1
    kind: Namespace
    state: present

- name: Add metallb helm repo for minio
  community.kubernetes.helm_repository:
    name: metallb
    repo_url: "https://metallb.github.io/metallb"

- name: Deploy metallb helm chart
  community.kubernetes.helm:
    name: metallb
    chart_ref: metallb/metallb
    chart_version: "{{ helm_chart_version_metallb | default(omit) }}"
    release_namespace: metallb-system

- name: Apply MetalLB pool configuration
  community.kubernetes.k8s:
    state: present
    template: 'template/pool.yaml.j2'

- name: Apply MetalLB L2 Advertisement configuration
  community.kubernetes.k8s:
    state: present
    template: 'template/l2adv.yaml.j2'
