---

- name: Create metallb-system namespace
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'files/namespace.yaml') }}"

- name: Apply MetalLB manifest
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'files/metallb.yaml') }}"

- name: Check if secretkey for MetalLB exists
  community.kubernetes.k8s_info:
    api_version: v1
    kind: Secret
    name: memberlist
    namespace: metallb-system
  register: metallb_secret_output

- name: Generate secretkey for MetalLB
  command: openssl rand -base64 128
  register: command_output
  when: metallb_secret_output['resources'] == []

- name: Create MetalLB memberlist secret
  community.kubernetes.k8s:
    state: present
    definition: 
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: memberlist
        namespace: metallb-system     
      data:
        secretkey: "{{ command_output.stdout }}"
  when: metallb_secret_output['resources'] == []

- name: Apply MetalLB configuration
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'template/config.yaml.j2') }}"
