---
- name: Check uptime
  command: uptime
  register: output

- debug: msg="{{ output.stdout }}"

- name: Ensure required packages from apt are installed.
  apt: 
    name: 
      - python-pip
      - nfs-common
    state: present

- name: Ensure k8s python module dependencies are installed.
  pip:
    name:
      - openshift

- name: Add plex_nfs_data_path to /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: "^{{ nfs_server_ip }}:{{ plex_nfs_data_path }}"
    line: "{{ nfs_server_ip }}:{{ plex_nfs_data_path }}	{{ plex_local_data_path }}	nfs	defaults	0	0"

- name: Mount plex_nfs_data_path on all cluster nodes
  ansible.posix.mount:
    src: "{{ nfs_server_ip }}:{{ plex_nfs_data_path }}"
    path: "{{ plex_local_data_path }}"
    fstype: nfs
    state: mounted
