---
- name: Check uptime
  command: uptime
  register: output

- debug: msg="{{ output.stdout }}"

- name: Ensure pip is installed.
  apt: 
    name: python-pip
    state: present

- name: Ensure k8s python module dependencies are installed.
  pip:
    name:
      - openshift
      #- k8s
      #- PyYAML
