---
- name: Check uptime
  command: uptime
  register: output

- debug: msg="{{ output.stdout }}"

- name: Ensure required packages from apt are installed.
  apt: 
    name: 
      - python-pip
      - nfs-common
    state: present

- name: Ensure k8s python module dependencies are installed.
  pip:
    name:
      - openshift
      #- k8s
      #- PyYAML
