---

- name: Create storage namespace
  community.kubernetes.k8s:
    name: storage
    api_version: v1
    kind: Namespace
    state: present

- name: Add nfs-subdir-external-provisioner helm repo
  community.kubernetes.helm_repository:
    name: nfs-subdir-external-provisioner
    repo_url: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/" 

- name: Deploy latest version of nfs-subdir-external-provisioner
  community.kubernetes.helm:
    name: storage
    chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    release_namespace: storage
    update_repo_cache: yes
    values:
      nfs:
        server: "{{ nfs_server_ip }}"
        path: "{{ nfs_server_path }}"
