---

- name: Create monitoring namespace
  community.kubernetes.k8s:
    name: monitoring
    api_version: v1
    kind: Namespace
    state: present

- name: Create persisitent volume claim for Grafana
  community.kubernetes.k8s:
    state: present
    template: 'template/grafana-nfs-pvc.yaml.j2'

- name: Create service for Prometheus
  community.kubernetes.k8s:
    state: present
    template: 'template/prometheus-web.yaml.j2'

- name: Create service for Grafana
  community.kubernetes.k8s:
    state: present
    template: 'template/grafana-web.yaml.j2'

- name: Add prometheus-community helm repo
  community.kubernetes.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"

- name: Deploy latest version of kube-prometheus-stack helm chart
  community.kubernetes.helm:
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: monitoring
    update_repo_cache: yes
    values: "{{ lookup('template', 'template/kube-prometheus-stack-values.yaml.j2') | from_yaml }}"
    wait: yes

- name: Deploy latest version of prometheus-snmp-exporter helm chart
  community.kubernetes.helm:
    name: snmp-exporter
    chart_ref: prometheus-community/prometheus-snmp-exporter
    release_namespace: monitoring
    values: "{{ lookup('template', 'template/prometheus-snmp-exporter-values.yaml.j2') | from_yaml }}"
    wait: yes
  tags:
    - prometheus_exporter

- name: Test for raspberry pi /proc/cpuinfo
  command: grep -E "Raspberry Pi|BCM2708|BCM2709|BCM2835|BCM2836" /proc/cpuinfo
  register: grep_cpuinfo_raspberrypi
  failed_when: false
  changed_when: false
  tags:
    - prometheus_exporter

- name: Test for raspberry pi /proc/device-tree/model
  command: grep -E "Raspberry Pi" /proc/device-tree/model
  register: grep_device_tree_model_raspberrypi
  failed_when: false
  changed_when: false
  tags:
    - prometheus_exporter

- name: Set raspberry_pi fact to true
  set_fact:
    raspberry_pi: true
  when:
    grep_cpuinfo_raspberrypi.rc == 0 or grep_device_tree_model_raspberrypi.rc == 0
  tags:
    - prometheus_exporter

- name: Apply arm_exporter manifest
  community.kubernetes.k8s:
    state: present
    template: 'template/armexporter.yaml.j2'
  when: raspberry_pi|default(false)
  tags: 
    - prometheus_exporter

- name: Create Grafana Kubernetes Dashboard
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'files/grafana-dashboard-k3s.yaml') }}"
