---

- name: Create storage namespace
  community.kubernetes.k8s:
    name: storage
    api_version: v1
    kind: Namespace
    state: present

- name: Add stable helm repo
  community.kubernetes.helm_repository:
    name: stable
    repo_url: "https://charts.helm.sh/stable" 

- name: Deploy latest version of nfs-client
  community.kubernetes.helm:
    name: nfs-client
    chart_ref: stable/nfs-client-provisioner
    release_namespace: storage
    update_repo_cache: yes
    values:
      nfs:
        server: "{{ nfs_server_ip }}"
        path: "{{ nfs_server_path }}"
