---

- name: Create minio namespace
  community.kubernetes.k8s:
    name: minio
    api_version: v1
    kind: Namespace
    state: present

- name: Create persisitent volume claim for Minio
  community.kubernetes.k8s:
    state: present
    template: 'template/minio-pvc.yaml.j2'

- name: Add minio helm repo for minio
  community.kubernetes.helm_repository:
    name: minio
    repo_url: "https://helm.min.io"

- name: Deploy Minio helm chart
  community.kubernetes.helm:
    name: mi
    chart_ref: minio/minio
    chart_version: "{{ helm_chart_version_minio | default(omit) }}"
    release_namespace: minio
    update_repo_cache: yes
    values: "{{ lookup('template', 'template/minio-values.yaml.j2') | from_yaml }}"
    wait: yes
